# Form implementation generated from reading ui file 'qltaiKhoan.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from tkinter import messagebox

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem

from BTL_Nhom09 import Login


class Ui_QuanLyTaiKhoanSinhVien(object):
    def setupUi(self, QuanLyTaiKhoanSinhVien):
        QuanLyTaiKhoanSinhVien.setObjectName("QuanLyTaiKhoanSinhVien")
        QuanLyTaiKhoanSinhVien.resize(598, 434)
        self.tblTaiKhoanSV = QtWidgets.QTableWidget(parent=QuanLyTaiKhoanSinhVien)
        self.tblTaiKhoanSV.setGeometry(QtCore.QRect(70, 150, 441, 192))
        self.tblTaiKhoanSV.setObjectName("tblTaiKhoanSV")
        self.tblTaiKhoanSV.setColumnCount(4)
        self.tblTaiKhoanSV.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoanSV.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoanSV.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoanSV.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoanSV.setHorizontalHeaderItem(3, item)
        self.txtTim = QtWidgets.QLineEdit(parent=QuanLyTaiKhoanSinhVien)
        self.txtTim.setGeometry(QtCore.QRect(240, 100, 181, 31))
        self.txtTim.setObjectName("txtTim")
        self.label_2 = QtWidgets.QLabel(parent=QuanLyTaiKhoanSinhVien)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnTim = QtWidgets.QPushButton(parent=QuanLyTaiKhoanSinhVien)
        self.btnTim.setGeometry(QtCore.QRect(430, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnTim.setFont(font)
        self.btnTim.setObjectName("btnTim")
        self.btnLoginForm = QtWidgets.QPushButton(parent=QuanLyTaiKhoanSinhVien)
        self.btnLoginForm.setGeometry(QtCore.QRect(350, 370, 81, 41))
        self.btnLoginForm.setObjectName("btnLoginForm")
        self.btnThoat = QtWidgets.QPushButton(parent=QuanLyTaiKhoanSinhVien)
        self.btnThoat.setGeometry(QtCore.QRect(450, 370, 81, 41))
        self.btnThoat.setObjectName("btnThoat")

        self.retranslateUi(QuanLyTaiKhoanSinhVien)
        QtCore.QMetaObject.connectSlotsByName(QuanLyTaiKhoanSinhVien)

        self.load_data()
        self.btnTim.clicked.connect(self.tim_kiem)
        self.btnThoat.clicked.connect(self.Thoat)

    def retranslateUi(self, QuanLyTaiKhoanSinhVien):
        _translate = QtCore.QCoreApplication.translate
        QuanLyTaiKhoanSinhVien.setWindowTitle(_translate("QuanLyTaiKhoanSinhVien", "QuanLyTaiKhoanSinhVien"))
        item = self.tblTaiKhoanSV.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyTaiKhoanSinhVien", "MaSV"))
        item = self.tblTaiKhoanSV.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyTaiKhoanSinhVien", "TenSV"))
        item = self.tblTaiKhoanSV.horizontalHeaderItem(2)
        item.setText(_translate("QuanLyTaiKhoanSinhVien", "User"))
        item = self.tblTaiKhoanSV.horizontalHeaderItem(3)
        item.setText(_translate("QuanLyTaiKhoanSinhVien", "Password"))
        self.label_2.setText(_translate("QuanLyTaiKhoanSinhVien", "Quản lý tài khoản SinhVien"))
        self.btnTim.setText(_translate("QuanLyTaiKhoanSinhVien", "Tìm kiếm"))
        self.btnLoginForm.setText(_translate("QuanLyTaiKhoanSinhVien", "Đăng nhập"))
        self.btnThoat.setText(_translate("QuanLyTaiKhoanSinhVien", "Thoát"))

    def load_data(self):
        conn = sqlite3.connect('ql_diemHeDH.db')
        cursor = conn.cursor()
        cursor.execute("""
            SELECT ql_HoSoSV.MaSV, ql_HoSoSV.TenSV, ql_TaiKhoan.User, ql_TaiKhoan.Password
            FROM ql_HoSoSV
            JOIN ql_TaiKhoan ON ql_HoSoSV.MaSV = ql_TaiKhoan.User
        """)
        data = cursor.fetchall()

        self.tblTaiKhoanSV.setRowCount(len(data))
        self.tblTaiKhoanSV.setColumnCount(4)
        self.tblTaiKhoanSV.setHorizontalHeaderLabels(['MaSV', 'TenSV', 'User', 'Password'])

        for i, row in enumerate(data):
            for j, value in enumerate(row):
                self.tblTaiKhoanSV.setItem(i, j, QTableWidgetItem(str(value)))

    def tim_kiem(self):
        search_term = self.txtTim.text()

        conn = sqlite3.connect('ql_diemHeDH.db')
        cursor = conn.cursor()
        cursor.execute("""
                    SELECT ql_HoSoSV.MaSV, ql_HoSoSV.TenSV, ql_TaiKhoan.User, ql_TaiKhoan.Password
                    FROM ql_HoSoSV
                    JOIN ql_TaiKhoan ON ql_HoSoSV.MaSV = ql_TaiKhoan.User
                    WHERE ql_HoSoSV.MaSV LIKE ? OR ql_HoSoSV.TenSV LIKE ? OR ql_TaiKhoan.User LIKE ? OR ql_TaiKhoan.Password LIKE ?
                """, (f'%{search_term}%', f'%{search_term}%', f'%{search_term}%', f'%{search_term}%'))
        data = cursor.fetchall()

        if data:
            self.tblTaiKhoanSV.setRowCount(len(data))
            self.tblTaiKhoanSV.setColumnCount(4)
            self.tblTaiKhoanSV.setHorizontalHeaderLabels(['MaSV', 'TenSV', 'User', 'Password'])

            for i, row in enumerate(data):
                for j, value in enumerate(row):
                    self.tblTaiKhoanSV.setItem(i, j, QTableWidgetItem(str(value)))
        else:
            messagebox.showinfo(self,"Thông báo","Không tìm thấy sinh viên")


    def Thoat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Login.Ui_Login_Dialog()
        self.ui.setupUi(self.window)
        Ui_QuanLyTaiKhoanSinhVien.hide()
        self.window.show()



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QuanLyTaiKhoanSinhVien = QtWidgets.QDialog()
    ui = Ui_QuanLyTaiKhoanSinhVien()
    ui.setupUi(QuanLyTaiKhoanSinhVien)
    QuanLyTaiKhoanSinhVien.show()
    sys.exit(app.exec())
